USE ROLE SYSADMIN;
USE DATABASE DB_CURSO;
USE SCHEMA PERFORMANCE;
USE WAREHOUSE WH_M08_CONC;

ALTER SESSION SET USE_CACHED_RESULT = FALSE;

ALTER SESSION SET QUERY_TAG =
    'M08_E02_ECONOMY_Q2';

SELECT *
FROM DB_CURSO.PERFORMANCE.V_CARGA_CONCURRENCIA
ORDER BY mes, region, canal;